---
- name: asignando contraseña de usuario root para mysql
  debconf:
   name: mysql-server
   question: mysql-server/root_password
   value: "{{ mysql_root_password }}"
   vtype: password

- name: asignando contraseña root para mysql
  debconf:
   name: mysql-server
   question: mysql-server/root_password_again
   value: "{{ mysql_root_password }}"
   vtype: password

- name: Instalacion de mysql y dependencias
  apt:
   pkg: "{{ item }}"
   state: installed
  with_items:
   - mysql-server
   - python-mysqldb

- name: MySQL | Set debconf vars
  action: raw echo mysql-server mysql-server/root_password PwdProof2017- $mysql_root_password | /usr/bin/debconf-set-selections
  tags: mysql

- name: MySQL | Set debconf vars
  action: raw echo mysql-server mysql-server/root_password_again PwdProof2017- $mysql_root_password | /usr/bin/debconf-set-selections
  tags: mysql

- name: install .my.cnf with credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf
            mode=0400
  tags: my_cnf

- name: definiendo directorio de mysql
  command: usermod -d /var/lib/mysql/ mysql

- name: Añadiendo configuracion y realizando backup de la original
  template:
   src: mysqld.cnf.j2
   dest: /etc/mysql/mysql.conf.d/mysqld.cnf
   owner: root
   group: root
   mode: 0644
   backup: yes

- name: Iniciando servicio mysql
  command: service mysql start
  register: start

- name: Respuesta de inicio
  debug: var=start

- name: Creando usuario mediawiki  con permisos de conexion externa
  mysql_user:
    login_user: "{{ mysql_root_usr }}"
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_media_usr }}"
    host: "{{ item }}"
    password: "{{ mysql_media_pwd }}"
    priv: "*.*:ALL,GRANT"
    state: present
  with_items:
   - 127.0.0.1
   - "localhost"
   - "%"
  notify:
   - restart mysql

- name: mediawiki DB creation with name mediawiki_db
  mysql_db:
    login_user: "{{ mysql_media_usr }}"
    login_password: "{{ mysql_media_pwd }}"
    name: mediawiki_db
    encoding: utf8
    state: present
